### ISSUE TITLE
NeonDatabase, based on pg15, can't load pgx extensions

### ISSUE THREAD

**Issue by vadim2404** [tcdi/pgx#1032]
For pg15, ABI is hardcoded to "PostgreSQL" and didn't get it from the source code, whereas C extensions get it and can be compiled.

**Comment by eeeebbbbrrrr** [comment]
I looked at your issue 3535 and, I mean, pgx only knows how to do the “PostgreSQL” ABI, not the custom “Neon PostgreSQL”. 

Now, I can imagine they’re actually the same but pgx cannot guarantee that. 

I might suggest you not change the ABI name if it’s actually the same.

**Comment by vadim2404** [comment]
> I looked at your issue 3535 and, I mean, pgx only knows how to do the “PostgreSQL” ABI, 

It's the issue. Is it possible to get the ABI name from PG sources while compiling extensions?

**Comment by eeeebbbbrrrr** [comment]
This is from the Postgres sources in `src/include/pg_config_manual.h`:

```c
/*
 * When creating a product derived from PostgreSQL with changes that cause
 * incompatibilities for loadable modules, it is recommended to change this
 * string so that dfmgr.c can refuse to load incompatible modules with a clean
 * error message.  Typical examples that cause incompatibilities are any
 * changes to node tags or node structures.  (Note that dfmgr.c already
 * detects common sources of incompatibilities due to major version
 * differences and due to some changed compile-time constants.  This setting
 * is for catching anything that cannot be detected in a straightforward way.)
 *
 * There is no prescribed format for the string.  The suggestion is to include
 * product or company name, and optionally any internally-relevant ABI
 * version.  Example: "ACME Postgres/1.2".  Note that the string will appear
 * in a user-facing error message if an ABI mismatch is detected.
 */
#define FMGR_ABI_EXTRA          "PostgreSQL"
```

Whatever "Neon PostgreSQL" is indicates that this is an ABI that is not compatible with "PostgreSQL".  "PostgreSQL" is the only ABI that pgx understands.

This is a new feature in pg15, that came in this commit:

```
commit d6d1dfcc99e3dd6e70e2a7024924e491bb7a9670
Author: Peter Eisentraut <peter@eisentraut.org>
Date:   Mon Nov 22 07:40:17 2021 +0100

    Add ABI extra field to fmgr magic block
    
    This allows derived products to intentionally make their fmgr ABI
    incompatible, with a clean error message.
    
    Discussion: https://www.postgresql.org/message-id/flat/55215fda-db31-a045-d6b7-d6f2d2dc9920%40enterprisedb.com
```

Technically, pgx can use whatever string we want but pgx only understands the "PostgreSQL" ABI.  As such, if "Neon PostgreSQL" were to deviate from this, then your extensions would be broken in unknown ways.

If "Neon PostgreSQL" and the real "PostgreSQL" have an identical function call ABI, then Neon shouldn't change the ABI name via this FMGR_ABI_EXTRA define.

**Comment by vadim2404** [comment]
All these comments are correct. However, Neon is not only a custom Postgresql. Postgres is ab open-source RDBMS, and there are a lot of forks.

What about adding the ability to define this option via env var or any other compilation flags for `pgx`?

**Comment by eeeebbbbrrrr** [comment]
As of v15, this ABI "name" is not a just some string to be changed.  It is a contract.  

It is a legally binding agreement between a loadable extension and the Postgres-based server that they speak the exact same ABI.  If they don't, Postgres refuses to load that extension, as you're seeing.

pgx **ONLY** knows how to speak the default "PostgreSQL" ABI.  It does not know what "Neon PostgreSQL"'s function call ABI is, nor can it know how (or when) the "Neon PostgreSQL" ABI might change in the future.

If, in fact, the "Neon PostreSQL" ABI is actually 100% identical to the default "PostgreSQL" ABI, then Neon **should NOT** change its ABI name.

Forking Postgres is not just simply a matter of changing all occurrences of "PostgreSQL" to "Something Else" in the source code.  It involves honoring the contracts that Postgres puts in place.  Most especially those that interact with open-source projects like pgx.

**Comment by vadim2404** [comment]
I meant to have sth like this. 

In Neon, we change the storage and compile extensions on our own to check the compatibility. 

However, I can't easily compile rust extensions because of this mismatch. I do agree that, in some cases, it'll require changes. However, I do expect that the majority of extensions can be compiled without any modifications.

```diff
diff --git a/pgx/src/lib.rs b/pgx/src/lib.rs
index 632686b..775bb17 100644
--- a/pgx/src/lib.rs
+++ b/pgx/src/lib.rs
@@ -188,6 +188,7 @@ macro_rules! pg_magic_func {
         #[doc(hidden)]
         pub extern "C" fn Pg_magic_func() -> &'static pgx::pg_sys::Pg_magic_struct {
             use core::mem::size_of;
+            use std::option_env;
             use pgx;

             #[cfg(any(feature = "pg11", feature = "pg12"))]
@@ -221,7 +222,7 @@ macro_rules! pg_magic_func {
                 float8byval: cfg!(target_pointer_width = "64") as i32,
                 abi_extra: {
                     // array::from_fn isn't const yet, boohoo, so const-copy a bstr
-                    let magic = b"PostgreSQL";
+                    let magic = option_env!("CUSTOM_ABI").unwrap_or("PostgreSQL").as_bytes();
                     let mut abi = [0 as ::pgx::ffi::c_char; 32];
                     let mut i = 0;
                     while i < magic.len() {
 ```

**Comment by vadim2404** [comment]
I understand your point.

But, look at the PostGIS extension. It was easily compiled with custom-defined ABI, unit extension (it's written on C) — again. Why can't I follow the same logic with `pgx` written extension?

**Comment by eeeebbbbrrrr** [comment]
One other thing to point out is that pgx will probably behave the way you want if it uses bindings generated from Neon.

You're likely compiling your extension against the stock Postgres source headers, and should instead use the Neon ones.

You've provided no information on how your extension is being compiled, but there are options to the various `cargo pgx` commands (including to `cargo pgx init`) to use different Postgres sources and different `pg_config` binaries than our defaults.

But you need to understand that if the "Neon PostgreSQL" ABI ever deviates from the standard "PostgreSQL", pgx won't understand that.

>  look at the PostGIS extension. It was easily compiled with custom-defined ABI

Sure, you probably used Neon's "pg_config", which used Neon's headers.

**Comment by vadim2404** [comment]
My bad: https://github.com/neondatabase/neon/blob/main/Dockerfile.compute-node — here is a docker file that describes how we built extensions

frankly saying, not all extensions require `pg_config`

It's a [PR](https://github.com/neondatabase/neon/pull/3535) where I've built the `pg_jsonschema` using `pgxz

**Comment by eeeebbbbrrrr** [comment]
I'm sorry, I misspoke.  pgx does indeed hard-code the "PostgreSQL" ABI.  My comment about using the Neon sources won't change anything.

But my point still stands.  pgx only understands the "PostgreSQL" ABI.  PostGIS compiles because it blindly gets that value from the Postgres source headers.  pgx hardcodes it (for pg15).

I don't know how to be more clear.  The "Neon PostgreSQL", because it isn't "PostgreSQL" is a different and explicitly incompatible ABI.  The Neon database made this decision.  You might as well be asking why MySQL won't load a pgx extension.

**Comment by vadim2404** [comment]
>  PostGIS compiles because it blindly gets that value from the Postgres source headers. pgx hardcodes it (for pg15).

And we returned to the beginning of our conversation.

The comparison with MySQL is exaggerated. The list of forks that potentially might have the same issue https://wiki.postgresql.org/wiki/PostgreSQL_derived_databases

For me, it sounds logical to parse this header and get the value from there. Like you do for other vars

**Comment by eeeebbbbrrrr** [comment]
> For me, it sounds logical to parse this header and get the value from there. Like you do for other vars

We can do that.  We can get it directly from `pg_config_manual.h` just like regular extensions, such as PostGIS, would via their use of the "PGXS" machinery in the Postgres Makefiles.

And I think you've persuaded me that we should.  I admit that there's probably a problem with a pgx-based extension being compiled against Neon's bindings but claiming it was compiled against Postgres' bindings.

But...

I'm not convinced that's improves pgx in any way nor am I convinced that offers any kind of guarantee that pgx, which is designed against the known "PostgreSQL" ABI, will actually work correctly if this "Neon PostgreSQL" ABI deviates, even in the slightly, from "PostgreSQL".

And while the comparison to MySQL is definitely exaggerated, my point still the same.  pgx has to have a much deeper understanding of how Postgres internals work, than say, a "regular" extension like PostGIS.  pgx is developed against the reference implementation that is Postgres itself.  When a fork, like Neon, comes along and explicitly says "We are consciously making this very low-level contract different", which Neon has done in this case, all bets are off that pgx will actually work with it.  

It may be that the Rust compiler will pick up differences if structs change, but if there's other changes, expectations, or inferences that the compiler can't detect, then pgx-based extensions compiled against Neon might not work.

And then the concern becomes: who's responsibility is that?  pgx isn't at a v1.0 release yet and I don't know if we're ready to proclaim that we support arbitrary Postgres forks too.  BTW, that list of forks on the Postgres wiki is wildly out of date.  Yikes!

Why did Neon decide that its ABI is different?

**Comment by eeeebbbbrrrr** [comment]
I've put up a PR:  https://github.com/tcdi/pgx/pull/1033

But I'd love an answer to:  Why did Neon decide that its ABI is different?

**Comment by vadim2404** [comment]
@eeeebbbbrrrr thanks for the PR. Appreciate it

I've asked the developers about this decision

**Comment by workingjubilee** [comment]
I actually think comparing against MySQL is not far enough.

Code compiled for Windows and code compiled for Linux generally cannot interoperate because they use different ABIs. Even when you can run the code on the same hardware, in many places, different registers are used for parameter passing and return values, or the same registers are given different meanings, so the same function will be addressed in different ways on different OS. To say nothing of how most of the available system functions and structures are different! No one expects a Linux program to run on Windows or vice versa without engaging some kind of compatibility layer like Wine or WSL that handles these differences. This is what an ABI **is**.

By changing the ABI string, you are *explicitly* stating that to build and run code on your database is *at least* as different as building and running code for *an entirely different OS*. For intractable, functional reasons.

Inside the PGX library, there are embedded assumptions that hinge on "this is how Postgres does data layout". Things that are **not** visible via merely binding against C structures and functions, either because they come from rules and conventions on how that code should be used, or because we cannot easily bind against macro definitions that are used in C, because Rust does not embed the C preprocessor in the language (thank Ferris). If you change how things like Postgres conventional data layout happens, you **will** break PGX. It will cause undefined behavior. And that is what changing the ABI string means.

It is not some "brand name" to change for marketing purposes. It does not matter if your database is named "The Most Excellent Supercalifragilisticexpialidocious Database". If it is a fork of Postgres that uses *the same function manager ABI*, it should and **must** use the same ABI string, `"PostgreSQL\0"`. So if NeonDatabase does not change anything that affects the ABI, then it should not change the ABI string. If it does, PGX cannot be expected to work with it.

Thus, according to what you are saying,

> However, I can't easily compile rust extensions because of this mismatch. I do agree that, in some cases, it'll require changes. However, I do expect that the majority of extensions can be compiled without any modifications.

Either it should not, in fact, be a different ABI string, or all bets are off and something as simple as our array functionality may break.

**Comment by eeeebbbbrrrr** [comment]
We've raised in issue over in Neon's repo:  https://github.com/neondatabase/neon/issues/3539

**Comment by vadim2404** [comment]
Guys, I'm here to thank you one more time for your efforts! We have already switched to an upgraded `pgx` version that includes this fix, and we have adopted 3rd parties extension for us!
