### ISSUE TITLE
`cargo pgx package` target destination should not rely on pg_config?

### ISSUE THREAD

**Issue by skyzh** [tcdi/pgx#1045]
When I was doing:

```
cargo pgx package -c /Users/skyzh/.pgx/15.2/pgx-install/bin/pg_config
```

It seems that the files are copied to:

```
     Copying control file to target/release/db721_fdw-pg15/Users/skyzh/.pgx/15.2/pgx-install/share/postgresql/extension/db721_fdw.control
     Copying shared library to target/release/db721_fdw-pg15/Users/skyzh/.pgx/15.2/pgx-install/lib/postgresql/db721_fdw.so
```

due to `base_directory` is set to my cargo target directory `/Users/skyzh/Work/fdw721/target/release/db721_fdw-pg15`:

https://github.com/tcdi/pgx/blob/24ad866922b312e51e71b568f4a955e0ac74afdd/cargo-pgx/src/command/install.rs#L108

I'm not sure how Postgres community packages and releases an extension. Would it make more sense to copy the extension artifacts to

```
db721_fdw.so -> target/release/db721_fdw-pg15/lib
db721_fdw.control -> target/release/db721_fdw-pg15/share
```

... so that we can have a deterministic path for all packaged extensions regardless of pg_config? Thanks!

(I can submit a PR to change the behavior of `cargo pgx package` if this makes sense...)

**Comment by eeeebbbbrrrr** [comment]
Heh.  `cargo pgx package` and `cargo pgx install` are **specifically** designed to use the `pg_config` on the $PATH.  While you can specify `-c/--pg-config`, specifying the one pgx itself installs/manages really isn't the intended use.

The idea with `cargo pgx pacakge` is that it builds up a directory structure based on where (distro-package-manager-installed) `pg_config` says files should go.  Then you'd come along after and create a .deb/.rpm/.apk package with those files, already laid out in the right structure.  It's meant to help packaging an extension in a way that's compatible with $some_linux_distro.

This is intentional behavior and been around for a few years.  Changing it isn't really on the table.

**Comment by skyzh** [comment]
Thanks for the explanation!
