### ISSUE TITLE
Multiple issues with `package`

### ISSUE THREAD

**Issue by vabatta** [tcdi/pgx#1098]
Hi,

I've been playing around a little bit with `pgx` and found quite a few issues related to `package`.

#### Issue `--no-default-features` is not considered

Steps to reproduce: 
1. Run `cargo pgx package --no-default-features -F pg15` 
2. See error
   - `Error: Multiple 'pg$VERSION' features found, '--no-default-features' may be required.`

#### Issue to run build command `pgx-pg-sys v0.7.4`

Steps to reproduce:
1. Run `cargo pgx package -F pg15`
2. See error
   - `failed to run custom build command for 'pgx-pg-sys v0.7.4'`

#### Issue `couldn't read postmaster` when `package` default feature (`pg13`)

Steps to reproduce:
1. Run `cargo pgx package` (for default feature `pg13: extension with features pg13`) 
2. After `Discovering SQL entities`, see error
```
Error: 
   0: couldn't read postmaster
   1: No such file or directory (os error 2)
```

Note: `pgx schema` works without issues

#### Repo to reproduce the above issues

1. Download https://github.com/vabatta/pg_base32
2. Open the dev container

**Comment by eeeebbbbrrrr** [comment]
here's what's going on here...  

`cargo pgx package` will default to using the `pg_config` on your `PATH` or the `-c` argument, and that's where it ultimately gets its feature detection from.  So what you want to do, based on the Cargo.toml in your repo:

```bash
$ cargo pgx package -c /path/to/postgres-v13/bin/pg_config --no-default-features
```

`cargo pgx package` is different from `cargo pgx run`.  By design, it doesn't (want to) use the Postgres instances compiled and locally installed/managed by `cargo pgx init`.  It wants you to specify the `pg_config` of a distro-installed Postgres package so that it can determine the proper directory tree for the extension artifacts.  If you don't specify the `pg_config` with `-c` then it defaults to what's on the `PATH`.
