### ISSUE TITLE
`extension_sql_file` does not respect order

### ISSUE THREAD

**Issue by olirice** [tcdi/pgx#556]
When multiple instances of `extension_sql_file` are present, their ordering in does not match the order from source, and is not deterministic.

For example:
```rust
extension_sql_file!("sql/pg/is_array.sql");
extension_sql_file!("sql/pg/to_is_composite.sql");
extension_sql_file!("sql/pg/to_regclass.sql");
```

Can result in:
```sql
-- src/lib.rs:25
create function x.is_array(regtype)
...

-- src/lib.rs:27
create function x.to_regclass(schema_ text, name_ text)
...

-- src/lib.rs:26
create function xl.is_composite(regtype)
...
```

The fastest way to reproduce is to include several SQL files as shown ^ and run 

```
cargo pgx schema > schema1.sql
cargo pgx schema > schema2.sql
diff schema1.sql schema2.sql
```
(note: you might have to run it more than once to see the behavior)

**Comment by Hoverbear** [comment]
Hi! Yup, this is because `pgx` can't know they're dependencies. :(

Please include the identifiers in the `required` field: https://docs.rs/pgx/latest/pgx/macro.extension_sql.html#

```rust
extension_sql_file!("sql/pg/is_array.sql");
extension_sql_file!("sql/pg/to_is_composite.sql", requires = [ "is_array" ]);
extension_sql_file!("sql/pg/to_regclass.sql", requires = [ "to_is_composite" ]);
```

(The names are inferred as so: https://docs.rs/pgx/latest/pgx/macro.extension_sql_file.html#)
![image](https://user-images.githubusercontent.com/130903/167211544-f80e47ab-5c58-4008-8722-014bdaa9108e.png)

**Comment by olirice** [comment]
Doh! I knew that at one point

sorry for the noise, that works great
