### ISSUE TITLE
Missing mapping for fdw_handler

### ISSUE THREAD

**Issue by film42** [tcdi/pgx#587]
In older versions I aliased the type like this...

```
type fdw_handler = pgx::PgBox<pgx_pg_sys::FdwRoutine>;
```

Now I get the error:

```
1: Failed to map return type `pgx::pgbox::PgBox<pgx_pg_sys::pg13::FdwRoutine>` to SQL type while building function `hello_fdw::hello_fdw_handler`.
```

**Comment by Hoverbear** [comment]
Thanks for reporting this! #588 should fix it.

If you want to use it, you'll need to depend on the branch in your crate and install `cargo-pgx` from that branch too. We're breaking some things next version bump so you may need to do a bit of poking. You're welcome to @ me on discord (we already chatted) and I'll help you do any migration steps, since we haven't written a guide yet.

If you feel like it sometime, I'd love to receive a PR making that test I added in #588 into something functional. :)
