### ISSUE TITLE
`cargo-pgx` should verify compiler parity requirement

### ISSUE THREAD

**Issue by Smittyvb** [tcdi/pgx#774]
pgx requires that the compiler used to compile `cargo-pgx` is the same compiler used to compile extension crates (https://github.com/tcdi/pgx/pull/687#discussion_r970745123), but doesn't verify that requirement in `cargo-pgx`. It should.

This requirement is not made obvious to users and results in user confusion since a compiler mismatch can result in weird segfaults and errors.

**Comment by workingjubilee** [comment]
We could have the Rust compiler version get injected into `cargo-pgx` via a `build.rs` or something like that.

**Comment by thomcc** [comment]
Do we need this except for the ability to return `eyre::Result` from that function? It might be better to just fix that requirement by returning something FFI safe.

**Comment by thomcc** [comment]
Ah, I see. Yeah, nevermind then.

**Comment by thomcc** [comment]
We do generate a lot of code so we could probably do better than JSON, but still, a problem for another time.

**Comment by thomcc** [comment]
FWIW, I think actually JSON would be fine here since this is only used in `cargo-pgx`, IIUC. I'll probably change to this soon since I've hit it many times recently, since I use nightly rust locally, and there have been changes to struct layout between stable and nightly, which caused me headache when debugging an issue that seemed to only appear on stable (it was actually just that the bug was non-deterministic).

That said, a better approach is probably to store this data in a custom `#[link_section]`, rather than returning it from a function, and then read it out in cargo-pgx (for example, with the `object` crate). Then we don't have to dlopen it, which will simplify the `schema` subcommand, and avoid the need for some crimes I'm going to have to do to fix #731.
