### ISSUE TITLE
Investigate if String::into_datum() and &str::into_datum() can be optimised

### ISSUE THREAD

**Issue by osawyerr** [tcdi/pgx#941]
Calling String::into_datum() and &str::into_datum() seem to take a lot of time. 

Running a trace in a profiler when selecting 300 million rows, String::into_datum() showed up as taking 25-30% of the total query time. For a "simple" conversion to a Datum this seemed quite excessive.

This issue is to investigate if this conversion can be optimised.

**Comment by yrashk** [comment]
Can you show the test code (at least its shape)? I presume `String::into_datum` was used to pass a query parameter?

**Comment by yrashk** [comment]
Ultimately, though, my understanding is that because we have to convert to `text` type (which is `varlena` -- a contiguous array of bytes preceded by its length), we have to copy Rust's string into it. The same logic applies to vectors.

The same is done by `cstring_to_text_with_len` in Postgres; it calls `memcpy`.

So it seems that the copying overhead is unavoidable if we want to use these Rust types. That being said, I am curious to see if we can introduce Postgres-backed data types that do not necessitate copying, some PgBox/PgVarlena/heapless::String<N> amalgamation (NB: `heapless::String` is [not `Copy`](https://github.com/japaric/heapless/issues/230) so can't be used in `PgVarlena`) and a counterpart for vectors. They'd be allocated in Postgres and won't need to be copied, but they might not be as convenient to use from Rust.

**Comment by yrashk** [comment]
The FFI overhead is unfortunate, but I think it's unavoidable as `cstring_to_text_with_len` can throw an error.

**Comment by osawyerr** [comment]
I have a broader question about FFI as well. Since it's used in quite a lot of places in PGX, is there a better way to handle possible errors that propagate from Postgress functions? It seems to add a lot of overhead (in general) and in a lot of case, we can't avoid using functions that use FFI if we're writing IAM or FDW.

**Comment by yrashk** [comment]
FFI wrappers are necessary because Postgres uses setjmp/longjmp for its error reporting, and it is (obviously) oblivious to Rust (or, well, any language with non-trivial or hidden control flow)

**Comment by EdMcBane** [comment]
See also https://github.com/tcdi/pgx/issues/356 where the issue of pg_guard overhead was discussed.

**Comment by eeeebbbbrrrr** [comment]
With a bit of work, basically just porting Postgres' `cstring_to_text` function to rust, my little test goes from

```sql
[v13.8][32312] strings=# explain analyze select strings.return_static() from generate_series(1, 1000000);
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 Function Scan on generate_series  (cost=0.00..12500.00 rows=1000000 width=32) (actual time=80.115..155.940 rows=1000000 loops=1)
 Planning Time: 0.070 ms
 Execution Time: 175.265 ms
(3 rows)
```

to

```sql
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 Function Scan on generate_series  (cost=0.00..12500.00 rows=1000000 width=32) (actual time=54.717..121.430 rows=1000000 loops=1)
 Planning Time: 0.015 ms
 Execution Time: 140.480 ms
(3 rows)
```

So what's that, about 20% faster?

There's still a trip through a `#[pg_guard]` for the call to palloc, but we cannot avoid that as palloc can raise an ERROR if there's not enough memory.

I'll have a PR up in a minute or two.

**Comment by eeeebbbbrrrr** [comment]
It's the function in `pgx-examples/strings/src/lib.rs`.

**Comment by osawyerr** [comment]
> FFI wrappers are necessary because Postgres uses setjmp/longjmp for its error reporting, and it is (obviously) oblivious to Rust (or, well, any language with non-trivial or hidden control flow)

Abit of a left-field question about the FFI wrapper... is it possible to group calls so that we only pay the FFI cost once per multiple calls to PG functions? This is coming from a Java guy so not sure it's feasible or if it'd make a difference to performance or not. Can this be done via annotations? I'm thinking along the lines of Spring Boot (Java framework) where transactions, etc are handle transparently by simply annotating a method. If an exception is thrown anywhere down the stack, it's detected and rolled back.

**Comment by eeeebbbbrrrr** [comment]
> is it possible to group calls so that we only pay the FFI cost once per multiple calls to PG functions

I just put up a PR to make the `pg_guard_ffi_boundary` public, so it's closer to being possible, if you want to declare your own `extern "C"` blocks for the Postgres functions you plan to use (bad idea and gross), but it still doesn't get you everything you want.  For example:

```rust
pgx::pg_sys::ffi::pg_guard_ffi_boundary(|| {
   // call FFI function
   let data = vec![1, 2, 3, 4, 5];
   // call FFI function that raises an ERROR
});
```

In the above example, `data` would never get dropped.  The only way to ensure proper Rust drop semantics during stack unwinding, at least right now, is to guard each function individually.

@thomcc has mentioned some things to me about what Rust itself is doing to make its story around set/longjmp better, but I'm not clear on the technical details there and if it would eventually let us get rid of our wrappers entirely.

I do wish we didn't need this, not just for the technical reasons, but because I'm tired of every-so-often having to justify how Postgres works, how Rust works, and why pgx is doing the only thing it can.

**Comment by thomcc** [comment]
Yeah, I think even if Rust implements those we wouldn't be able to do that in most cases, as it would still be UB to long non-"plain ol' frames" -- stack frames that require running destructors.

**Comment by eeeebbbbrrrr** [comment]
This got merged, so closing.
